version: "3.7"

services:
  backend:
    # image: node:12-alpine
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    env_file: ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./backend:/app
    restart: on-failure

  frontend:
    # image: node:12-alpine
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file: ./frontend/.env
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/app
    restart: on-failure
